# Generated by Django 5.2.1 on 2025-07-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleOS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='data_solicitacao',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_faturamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='faturado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='previsao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('nao_iniciado', 'Não Iniciado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído')], default='nao_iniciado', max_length=20),
        ),
    ]
