# Generated by Django 5.2.1 on 2025-07-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleOS', '0002_remove_ordemservico_data_solicitacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='data_solicitacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Solicitação'),
        ),
    ]
