# Generated by Django 5.2.1 on 2025-07-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleOS', '0003_ordemservico_data_solicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='horas_consumidas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='total_faturar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
