# Generated by Django 5.2.1 on 2025-08-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lancamentofinanceiro',
            old_name='favorecido',
            new_name='cliente',
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='tipo',
            field=models.CharField(choices=[('Receita', 'Receita'), ('Despesa', 'Despesa')], max_length=10),
        ),
    ]
