# Generated by Django 5.2.1 on 2025-08-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_rename_favorecido_lancamentofinanceiro_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='codigo_pagamento',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
