# Generated by Django 5.2.1 on 2025-08-19 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_alter_lancamentofinanceiro_codigo_pagamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lancamentofinanceiro',
            old_name='codigo_pagamento',
            new_name='codigo_barras',
        ),
    ]
