# Generated by Django 5.2.1 on 2025-09-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_rename_codigo_pagamento_lancamentofinanceiro_codigo_barras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
