# Generated by Django 5.2.1 on 2025-07-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cnpj', models.CharField(max_length=20)),
                ('razao_social', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Física', 'Física'), ('Jurídica', 'Jurídica')], max_length=10)),
                ('endereco', models.TextField()),
                ('modalidade', models.CharField(choices=[('Contrato', 'Contrato'), ('Hora', 'Hora'), ('Projeto', 'Projeto')], max_length=10)),
                ('valor_cobranca', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_faturamento', models.DateField()),
                ('data_vencimento', models.DateField()),
            ],
        ),
    ]
