# Generated by Django 5.2.1 on 2025-07-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='data_vencimento',
        ),
        migrations.AddField(
            model_name='cliente',
            name='vencimento_dia',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Informe o dia do mês para vencimento (1 a 31)', null=True, verbose_name='Dia de Vencimento'),
        ),
    ]
